In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("data-sets/olympics.csv", skiprows=[0,1], header=
                 names=['Country','SummerGames','S-Gold', 'S-Silver', 'S-Bronze','S-Total', 'WinterGames','W-Gold', 'W-Silver', 'W-Bronze','W-Total', 'TotalGames','Gold', 'Silver', 'Bronze', 'CombinedTotal'])

In [53]:
df.shape

(147, 16)

In [56]:
df.head()

,Country,SummerGames,S-Gold,S-Silver,S-Bronze,S-Total,WinterGames,W-Gold,W-Silver,W-Bronze,W-Total,TotalGames,Gold,Silver,Bronze,CombinedTotal
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
2,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
3,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
4,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country        147 non-null    str
 1   SummerGames    147 non-null    int64
 2   S-Gold         147 non-null    int64
 3   S-Silver       147 non-null    int64
 4   S-Bronze       147 non-null    int64
 5   S-Total        147 non-null    int64
 6   WinterGames    147 non-null    int64
 7   W-Gold         147 non-null    int64
 8   W-Silver       147 non-null    int64
 9   W-Bronze       147 non-null    int64
 10  W-Total        147 non-null    int64
 11  TotalGames     147 non-null    int64
 12  Gold           147 non-null    int64
 13  Silver         147 non-null    int64
 14  Bronze         147 non-null    int64
 15  CombinedTotal  147 non-null    int64
dtypes: int64(15), str(1)
memory usage: 18.5 KB

In [37]:
(df.loc[:, "S-Total"] + df.loc[:, "W-Total"] == df.loc[:,"CombinedTotal"]).value_counts()

True    147
Name: count, dtype: int64

In [49]:
df[["S-Bronze","W-Bronze"]]

     S-Bronze  W-Bronze
0           2         0
1           8         0
2          28         0
3           9         0
4           5         0
..        ...       ...
142         2         0
143         1         0
144         1         0
145         4         0
146      5130       948

[147 rows x 2 columns]

In [58]:
import os

In [67]:
with open("data-sets/university_towns.txt", "r") as file:
    state = ""
    university_rows = []
    for line in file:
        if line.strip().endswith("[edit]"):
            state = str(line).split("[")[0]
            # print(state)
        elif line.strip().endswith(":"):
            state = str(line).split(":")[0]
        else:
            town = line.split(" (")[0]
            universities = line.split(" (")[1]
            # print(f"  town: {town}")
            # print(f"      universities: {universities}")

        if town and universities:
            university_rows.append([state, town, universities])
            town = ""
            universities = ""

# print(university_rows)
        
universities_df = pd.DataFrame(data = university_rows,
             columns=["state", "town", "universities"])

In [68]:
universities_df.tail(20)

,state,town,universities
494,West Virginia,Glenville,Glenville State College)[2]\n
495,West Virginia,Huntington,Marshall University)[2]\n
496,West Virginia,Montgomery,West Virginia University Institute of Technolo...
497,West Virginia,Morgantown,West Virginia University)[2]\n
498,West Virginia,Shepherdstown,Shepherd University)[2]\n
499,West Virginia,West Liberty,West Liberty University)[2]\n
500,Wisconsin,Appleton,Lawrence University)\n
501,Wisconsin,Eau Claire,University of Wisconsinâ€“Eau Claire)\n
502,Wisconsin,Green Bay,University of Wisconsin-Green Bay)\n
503,Wisconsin,La Crosse,"University of Wisconsinâ€“La Crosse, Western T..."
504,Wisconsin,Madison,University of Wisconsinâ€“Madison)[2]\n
505,Wisconsin,Menomonie,University of Wisconsinâ€“Stout)[2]\n
506,Wisconsin,Milwaukee,"Marquette University, University of Wisconsinâ..."
507,Wisconsin,Oshkosh,University of Wisconsinâ€“Oshkosh)\n
508,Wisconsin,Platteville,University of Wisconsinâ€“Platteville)[2]\n
509,Wisconsin,River Falls,University of Wisconsinâ€“River Falls)[2]\n
510,Wisconsin,Stevens Point,University of Wisconsinâ€“Stevens Point)[2]\n
511,Wisconsin,Waukesha,Carroll University)\n
512,Wisconsin,Whitewater,University of Wisconsinâ€“Whitewater)[2]\n
513,Wyoming,Laramie,University of Wyoming)[5]\n

In [71]:
def read_file():
        
    with open("data-sets/university_towns.txt", "r") as file:
        state = ""
        university_rows = []
        for line in file:
            if "[edit]" in line:
                state = line.strip()
            else:
                town = line.strip()
                university_rows.append([state, town])

    return pd.DataFrame(data = university_rows, columns = ["state", "town"])

In [ ]:
university_df = read_file()
university_df.to_csv("towns.csv")

In [73]:
university_df.head(7)

           state                                               town
0  Alabama[edit]                      Auburn (Auburn University)[1]
1  Alabama[edit]             Florence (University of North Alabama)
2  Alabama[edit]    Jacksonville (Jacksonville State University)[2]
3  Alabama[edit]         Livingston (University of West Alabama)[2]
4  Alabama[edit]           Montevallo (University of Montevallo)[2]
5  Alabama[edit]                          Troy (Troy University)[2]
6  Alabama[edit]  Tuscaloosa (University of Alabama, Stillman Co...

In [75]:
university_df = pd.read_csv("towns.csv", index_col=0)
university_df.head(7)

           state                                               town
0  Alabama[edit]                      Auburn (Auburn University)[1]
1  Alabama[edit]             Florence (University of North Alabama)
2  Alabama[edit]    Jacksonville (Jacksonville State University)[2]
3  Alabama[edit]         Livingston (University of West Alabama)[2]
4  Alabama[edit]           Montevallo (University of Montevallo)[2]
5  Alabama[edit]                          Troy (Troy University)[2]
6  Alabama[edit]  Tuscaloosa (University of Alabama, Stillman Co...

In [83]:
university_df = university_df.assign(state = university_df["state"].str.removesuffix("[edit]"))

In [84]:
university_df

         state                                               town
0      Alabama                      Auburn (Auburn University)[1]
1      Alabama             Florence (University of North Alabama)
2      Alabama    Jacksonville (Jacksonville State University)[2]
3      Alabama         Livingston (University of West Alabama)[2]
4      Alabama           Montevallo (University of Montevallo)[2]
..         ...                                                ...
511  Wisconsin  River Falls (University of Wisconsinâ€“River F...
512  Wisconsin  Stevens Point (University of Wisconsinâ€“Steve...
513  Wisconsin                      Waukesha (Carroll University)
514  Wisconsin  Whitewater (University of Wisconsinâ€“Whitewat...
515    Wyoming                 Laramie (University of Wyoming)[5]

[516 rows x 2 columns]

In [89]:
university_df = university_df.assign(town = university_df["town"].str.extract(pat = r"(.*) \(.*"))

In [90]:
university_df

         state           town       town_new
0      Alabama         Auburn         Auburn
1      Alabama       Florence       Florence
2      Alabama   Jacksonville   Jacksonville
3      Alabama     Livingston     Livingston
4      Alabama     Montevallo     Montevallo
..         ...            ...            ...
511  Wisconsin    River Falls    River Falls
512  Wisconsin  Stevens Point  Stevens Point
513  Wisconsin       Waukesha       Waukesha
514  Wisconsin     Whitewater     Whitewater
515    Wyoming        Laramie        Laramie

[516 rows x 3 columns]

In [123]:
books_df = (
    pd.read_csv("data-sets/BL-Flickr-Images-Book.csv", index_col=0)
    .rename(columns = lambda header : str(header).lower().replace(" ", "_"))
    )
books_df = books_df.rename_axis(index='id')

In [124]:
books_df.drop(labels = ["corporate_author", "corporate_contributors", "former_owner", "engraver", "edition_statement", "contributors", "issuance_type","shelfmarks"], axis = 1, inplace = True)

In [125]:
books_df.info()

<class 'pandas.DataFrame'>
Index: 8287 entries, 206 to 4160339
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   place_of_publication  8287 non-null   str
 1   date_of_publication   8106 non-null   str
 2   publisher             4092 non-null   str
 3   title                 8287 non-null   str
 4   author                6509 non-null   str
 5   flickr_url            8287 non-null   str
dtypes: str(6)
memory usage: 453.2 KB

In [126]:
books_df

,place_of_publication,date_of_publication,publisher,title,author,flickr_url
id,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...
4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.",http://www.flickr.com/photos/britishlibrary/ta...
4158128,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...",http://www.flickr.com/photos/britishlibrary/ta...
4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,http://www.flickr.com/photos/britishlibrary/ta...

In [1]:
import numpy as np
import pandas as pd

In [7]:
def rename_columns(name):
    return name.lower().replace(" ", "_")

In [53]:
df.info()

<class 'pandas.DataFrame'>
Index: 8287 entries, 206 to 4160339
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   place_of_publication  8287 non-null   str
 1   date_of_publication   8287 non-null   uint16
 2   publisher             4092 non-null   str
 3   title                 8287 non-null   str
 4   author                6509 non-null   str
 5   contributors          8287 non-null   str
 6   flickr_url            8287 non-null   str
 7   shelfmarks            8287 non-null   str
dtypes: str(7), uint16(1)
memory usage: 534.1 KB

In [51]:
def convert_date_to_numeric(df : pd.DataFrame):
    return pd.to_numeric(
        df["date_of_publication"].str.extract(r'(\d{4})', expand = False).fillna(0),
        downcast = 'unsigned'
        )

In [52]:
df = (pd.read_csv("data-sets/BL-Flickr-Images-Book.csv")
 .rename(columns= rename_columns)
 .rename(columns={"identifier" : "id"})
 .set_index("id")
 .drop(labels = ["edition_statement", "corporate_author", "corporate_contributors", "former_owner", "engraver", 'issuance_type'], axis= 1)
 .assign(date_of_publication = convert_date_to_numeric)
#  .date_of_publication.fillna(0)
#  .astype(dtype = {'date_of_publication' : np.int16})
)

df

,place_of_publication,date_of_publication,publisher,title,author,contributors,flickr_url,shelfmarks
id,,,,,,,,
206,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
...,...,...,...,...,...,...,...,...
4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
4158128,Derby,1831,M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
4159563,London,1806,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
4160339,London,1834,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

In [35]:
df.assign(date_of_publication = lambda df: df["date_of_publication"].str.extract(r'(\d{4})'), expand = False).fillna(0)

,place_of_publication,date_of_publication,publisher,title,author,contributors,flickr_url,shelfmarks,expand
id,,,,,,,,,
206,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.,False
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.,False
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.,False
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.,False
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.,False
...,...,...,...,...,...,...,...,...,...
4158088,London,1838,0,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...,False
4158128,Derby,1831,M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...,False
4159563,London,1806,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...,False
4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...,False
4160339,London,1834,0,Collectanea Topographica et Genealogica. [Firs...,0,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...,False

In [ ]:
pd.to_numeric()

In [2]:
import pandas as pd
import numpy as np

In [91]:
data = {
    "Name": ['Bob',"Bob", "Bob", "Ishi", "Masimo"],
    "Fruit" : ["Apple", "Pear", "Apple", "Pear", "Pear"]
}

df = pd.DataFrame(data =data, index = [2,5,6,8,11])

In [92]:
my_s = pd.Series(
    data = [1,2,1,2,1]
)
obj = df.groupby(by = my_s)["Name"]
obj.groups

{1.0: [2]}

In [64]:
def myfunc(num):
    if isinstance(num, int):
        print(num)
        return num % 2
    else:
        return -1
obj = df.groupby(by = myfunc)

for name, obj_df in obj:
    print(name)
    print(obj_df)
    print(type(obj_df))

obj.groups

2
5
6
8
11
0
   Name  Fruit
2   Bob  Apple
6   Bob  Apple
8  Ishi   Pear
<class 'pandas.DataFrame'>
1
      Name Fruit
5      Bob  Pear
11  Masimo  Pear
<class 'pandas.DataFrame'>

{0: [2, 6, 8], 1: [5, 11]}

In [67]:
pd.set_option("display.max_columns", None)

In [70]:
dtypes = {
    "gender" : "category",
    "type" : "category",
    "state" : "category",
    "party" : "category",
}

In [71]:
df = pd.read_csv(
    "data-sets/legislators-historical.csv",
    dtype = dtypes,
    usecols= list(dtypes.keys()) + ["birthday", "last_name"],
    parse_dates = ["birthday"]
    )

In [74]:
df

      last_name   birthday gender type state                party
0       Bassett 1745-04-02      M  sen    DE  Anti-Administration
1         Bland 1742-03-21      M  rep    VA                  NaN
2         Burke 1743-06-16      M  rep    SC                  NaN
3       Carroll 1730-07-22      M  rep    MD                  NaN
4        Clymer 1739-03-16      M  rep    PA                  NaN
...         ...        ...    ...  ...   ...                  ...
11970   Garrett 1972-03-27      M  rep    VA           Republican
11971    Handel 1962-04-18      F  rep    GA           Republican
11972     Jones 1959-10-24      F  rep    MI             Democrat
11973    Marino 1952-08-15      M  rep    PA           Republican
11974     Jones 1943-02-10      M  rep    NC           Republican

[11975 rows x 6 columns]

In [85]:
group_obj = df.groupby("state", sort = False)

In [86]:
for state, legislators in group_obj:
    print(state)
    print(legislators)

DE
      last_name   birthday gender type state                party
0       Bassett 1745-04-02      M  sen    DE  Anti-Administration
40         Read 1733-09-18      M  sen    DE                  NaN
93       Vining 1758-12-23      M  sen    DE           Federalist
129      Patten 1746-04-26      M  rep    DE           Republican
165     Latimer 1752-04-24      M  sen    DE           Federalist
...         ...        ...    ...  ...   ...                  ...
11151      Roth 1921-07-22      M  sen    DE           Republican
11532     Biden 1942-11-20      M  sen    DE             Democrat
11542    Castle 1939-07-02      M  rep    DE           Republican
11618   Kaufman 1939-03-15      M  sen    DE             Democrat
11816    Carney 1956-05-20      M  rep    DE             Democrat

[97 rows x 6 columns]
VA
       last_name   birthday gender type state                party
1          Bland 1742-03-21      M  rep    VA                  NaN
11       Grayson        NaT      M  sen    VA  Anti-Administration
18           Lee 1732-01-20      M  sen    VA  Anti-Administration
29        Walker 1744-02-13      M  sen    VA   Pro-Administration
52         White        NaT      M  rep    VA                  NaN
...          ...        ...    ...  ...   ...                  ...
11902  Goodlatte 1952-09-22      M  rep    VA           Republican
11948       Brat 1964-07-27      M  rep    VA           Republican
11961   Comstock 1959-06-30      F  rep    VA           Republican
11969     Taylor 1979-06-27      M  rep    VA           Republican
11970    Garrett 1972-03-27      M  rep    VA           Republican

[432 rows x 6 columns]
SC
      last_name   birthday gender type state               party
2         Burke 1743-06-16      M  rep    SC                 NaN
15        Izard        NaT      M  sen    SC  Pro-Administration
31     Barnwell 1761-12-21      M  rep    SC                 NaN
37        Huger 1742-02-20      M  rep    SC                 NaN
50       Tucker 1745-06-25      M  rep    SC                 NaN
...         ...        ...    ...  ...   ...                 ...
11606    Spratt 1942-11-01      M  rep    SC            Democrat
11720    DeMint 1951-09-02      M  sen    SC          Republican
11863  Mulvaney 1967-07-21      M  rep    SC          Republican
11903     Gowdy 1964-08-22      M  rep    SC          Republican
11947   Sanford 1960-05-28      M  rep    SC          Republican

[251 rows x 6 columns]
MD
      last_name   birthday gender type state       party
3       Carroll 1730-07-22      M  rep    MD         NaN
5        Contee        NaT      M  rep    MD         NaN
10         Gale 1756-06-03      M  rep    MD         NaN
24        Smith 1728-04-12      M  rep    MD         NaN
25        Stone        NaT      M  rep    MD         NaN
...         ...        ...    ...  ...   ...         ...
11573  Kratovil 1968-05-29      M  rep    MD    Democrat
11655  Bartlett 1926-06-03      M  rep    MD  Republican
11809  Mikulski 1936-07-20      F  sen    MD    Democrat
11818   Edwards 1958-06-28      F  rep    MD    Democrat
11941   Delaney 1963-04-16      M  rep    MD    Democrat

[305 rows x 6 columns]
PA
      last_name   birthday gender type state                party
4        Clymer 1739-03-16      M  rep    PA                  NaN
19       Maclay 1737-07-20      M  sen    PA  Anti-Administration
21       Morris 1734-01-20      M  sen    PA   Pro-Administration
27      Wynkoop 1737-03-02      M  rep    PA                  NaN
38       Jacobs 1726-06-09      M  rep    PA                  NaN
...         ...        ...    ...  ...   ...                  ...
11891     Brady 1945-04-07      M  rep    PA             Democrat
11932   Shuster 1961-01-10      M  rep    PA           Republican
11945   Rothfus 1962-04-25      M  rep    PA           Republican
11959  Costello 1976-09-07      M  rep    PA           Republican
11973    Marino 1952-08-15      M  rep    PA           Republican

[1053 rows x 6 columns]
MA
       last_name   birthday gender type state               party
6         Dalton 1738-05-28      M  sen    MA  Pro-Administration
12         Grout 1737-07-23      M  rep    MA                 NaN
22     Partridge 1740-02-08      M  rep    MA                 NaN
33         Cabot 1752-12-03      M  sen    MA          Federalist
36         Gerry 1744-07-17      M  rep    MA                 NaN
...          ...        ...    ...  ...   ...                 ...
11722      Kerry 1943-12-11      M  sen    MA            Democrat
11724      Cowan 1969-04-04      M  sen    MA            Democrat
11781    Tierney 1951-09-18      M  rep    MA            Democrat
11892    Capuano 1952-01-09      M  rep    MA            Democrat
11934    Tsongas 1946-04-26      F  rep    MA            Democrat

[426 rows x 6 columns]
NJ
           last_name   birthday gender type state               party
7              Elmer 1745-11-29      M  sen    NJ  Pro-Administration
23          Paterson 1745-12-24      M  sen    NJ  Pro-Administration
28         Dickinson 1739-04-05      M  sen    NJ  Pro-Administration
58            Beatty 1749-12-10      M  rep    NJ                 NaN
59          Boudinot 1740-05-02      M  rep    NJ                 NaN
...              ...        ...    ...  ...   ...                 ...
11825        Garrett 1959-07-09      M  rep    NJ          Republican
11901  Frelinghuysen 1946-04-29      M  rep    NJ          Republican
11913          Lance 1952-06-25      M  rep    NJ          Republican
11915       LoBiondo 1946-05-12      M  rep    NJ          Republican
11957      MacArthur 1960-10-16      M  rep    NJ          Republican

[359 rows x 6 columns]
GA
          last_name   birthday gender type state                party
8               Few 1748-06-08      M  sen    GA  Anti-Administration
20          Mathews 1739-08-30      M  rep    GA                  NaN
51            Wayne 1745-01-01      M  rep    GA                  NaN
54           Willis 1745-01-05      M  rep    GA                  NaN
63           Carnes        NaT      M  rep    GA                  NaN
...             ...        ...    ...  ...   ...                  ...
11757       Gingrey 1942-07-10      M  rep    GA           Republican
11762      Kingston 1955-04-24      M  rep    GA           Republican
11848  Westmoreland 1950-04-02      M  rep    GA           Republican
11862         Price 1954-10-08      M  rep    GA           Republican
11971        Handel 1962-04-18      F  rep    GA           Republican

[309 rows x 6 columns]
NY
            last_name   birthday gender type state       party
9               Floyd 1734-12-17      M  rep    NY         NaN
26     Van Rensselaer 1738-08-27      M  rep    NY         NaN
32               Burr 1756-02-06      M  sen    NY  Republican
42        Schoonmaker        NaT      M  rep    NY         NaN
46          Silvester        NaT      M  rep    NY         NaN
...               ...        ...    ...  ...   ...         ...
11872       Slaughter 1929-08-14      F  rep    NY    Democrat
11894         Crowley 1962-03-16      M  rep    NY    Democrat
11962         Donovan 1956-11-06      M  rep    NY  Republican
11967            Faso 1952-08-25      M  rep    NY  Republican
11968          Tenney 1961-02-04      F  rep    NY  Republican

[1461 rows x 6 columns]
NC
        last_name   birthday gender type state               party
13        Hawkins 1754-08-15      M  sen    NC  Pro-Administration
17       Johnston 1733-12-15      M  sen    NC  Pro-Administration
30           Ashe        NaT      M  rep    NC                 NaN
47         Steele 1764-11-16      M  rep    NC                 NaN
53     Williamson 1735-12-05      M  rep    NC          Federalist
...           ...        ...    ...  ...   ...                 ...
11766    McIntyre 1956-08-06      M  rep    NC            Democrat
11795       Coble 1931-03-18      M  rep    NC          Republican
11819     Ellmers 1964-02-09      F  rep    NC          Republican
11943   Pittenger 1948-08-15      M  rep    NC          Republican
11974       Jones 1943-02-10      M  rep    NC          Republican

[354 rows x 6 columns]
CT
        last_name   birthday gender type state               party
14     Huntington 1736-04-19      M  rep    CT                 NaN
16        Johnson 1727-10-07      M  sen    CT  Pro-Administration
35      Ellsworth 1745-04-29      M  sen    CT          Federalist
45        Sherman 1721-04-19      M  sen    CT  Pro-Administration
49        Sturges 1740-08-23      M  rep    CT                 NaN
...           ...        ...    ...  ...   ...                 ...
11424     Johnson 1935-01-05      F  rep    CT          Republican
11446     Simmons 1943-02-11      M  rep    CT          Republican
11516       Shays 1945-10-18      M  rep    CT          Republican
11643   Lieberman 1942-02-24      M  sen    CT         Independent
11939        Esty 1959-08-25      F  rep    CT            Democrat

[240 rows x 6 columns]
VT
      last_name   birthday gender type state                party
41     Robinson 1741-03-22      M  sen    VT  Anti-Administration
86        Niles 1741-04-03      M  rep    VT                  NaN
106        Buck 1753-11-09      M  rep    VT           Federalist
128       Paine 1757-01-21      M  sen    VT           Federalist
156     Chipman 1752-11-15      M  sen    VT           Federalist
...         ...        ...    ...  ...   ...                  ...
10034     Aiken 1892-08-20      M  sen    VT           Republican
10253   Mallary 1929-02-21      M  rep    VT           Republican
10696  Stafford 1913-08-08      M  sen    VT           Republican
10855     Smith 1945-10-31      M  rep    VT           Republican
11308  Jeffords 1934-05-11      M  sen    VT          Independent

[115 rows x 6 columns]
KY
       last_name   birthday gender type state                party
55       Edwards        NaT      M  sen    KY  Anti-Administration
113      Greenup        NaT      M  rep    KY           Republican
123     Marshall        NaT      M  sen    KY           Federalist
126          Orr 1761-11-06      M  rep    KY           Republican
196        Brown 1757-09-12      M  sen    KY           Republican
...          ...        ...    ...  ...   ...                  ...
11433    Northup 1948-01-22      F  rep    KY           Republican
11497      Lewis 1946-09-14      M  rep    KY           Republican
11625      Davis 1958-10-26      M  rep    KY           Republican
11669   Chandler 1959-09-12      M  rep    KY             Democrat
11801  Whitfield 1943-05-25      M  rep    KY           Republican

[373 rows x 6 columns]
RI
      last_name   birthday gender type state       party
61     Bradford 1729-11-04      M  sen    RI  Federalist
105      Bourne 1755-09-09      M  rep    RI  Federalist
161      Foster 1752-04-29      M  sen    RI  Republican
195       Brown 1736-01-27      M  rep    RI  Federalist
215      Greene 1765-02-02      M  sen    RI  Federalist
...         ...        ...    ...  ...   ...         ...
11050  Machtley 1948-07-13      M  rep    RI  Republican
11100    Chafee 1922-10-22      M  sen    RI  Republican
11270   Weygand 1948-05-10      M  rep    RI    Democrat
11287    Chafee 1953-03-26      M  sen    RI  Republican
11568   Kennedy 1967-07-14      M  rep    RI    Democrat

[107 rows x 6 columns]
NH
         last_name   birthday gender type state       party
99         Wingate 1739-05-14      M  rep    NH         NaN
120        Langdon 1741-06-26      M  sen    NH  Republican
134      Sherburne        NaT      M  rep    NH  Republican
180          Smith 1759-11-29      M  rep    NH  Federalist
184        Sprague 1756-12-10      M  rep    NH  Federalist
...            ...        ...    ...  ...   ...         ...
11563        Hodes 1951-03-21      M  rep    NH    Democrat
11656         Bass 1952-01-08      M  rep    NH  Republican
11805       Ayotte 1968-06-27      F  sen    NH  Republican
11855       Guinta 1970-09-26      M  rep    NH  Republican
11964  Shea-Porter 1952-12-02      F  rep    NH    Democrat

[181 rows x 6 columns]
TN
      last_name   birthday gender type state       party
141       White 1749-06-16      M  rep    TN         NaN
142      Blount 1749-03-26      M  sen    TN  Republican
198       Cocke        NaT      M  sen    TN  Republican
350     Dickson 1770-05-05      M  rep    TN  Republican
378       Smith 1748-10-29      M  sen    TN  Republican
...         ...        ...    ...  ...   ...         ...
11613      Wamp 1957-10-28      M  rep    TN  Republican
11821   Fincher 1973-02-07      M  rep    TN  Republican
11883    Corker 1952-08-24      M  sen    TN  Republican
11889     Black 1951-01-16      F  rep    TN  Republican
11898    Duncan 1947-07-21      M  rep    TN  Republican

[299 rows x 6 columns]
OH
      last_name   birthday gender type state       party
226    McMillan 1764-03-02      M  rep    OH         NaN
254     Fearing 1762-02-28      M  rep    OH  Federalist
326       Smith        NaT      M  sen    OH  Republican
443      Tiffin 1766-06-19      M  sen    OH  Republican
453       Meigs 1764-11-17      M  sen    OH  Republican
...         ...        ...    ...  ...   ...         ...
11707   Schmidt 1951-11-29      F  rep    OH  Republican
11712    Sutton 1963-07-31      F  rep    OH    Democrat
11799   Boehner 1949-11-17      M  rep    OH  Republican
11871    Tiberi 1962-10-21      M  rep    OH  Republican
11922   Renacci 1958-12-03      M  rep    OH  Republican

[674 rows x 6 columns]
MS
       last_name   birthday gender type state       party
256       Greene 1758-02-26      M  rep    MS         NaN
260       Hunter        NaT      M  rep    MS         NaN
743    Lattimore 1774-02-09      M  rep    MS         NaN
842        Leake 1762-05-25      M  sen    MS  Republican
994       Holmes 1769-03-10      M  sen    MS  Republican
...          ...        ...    ...  ...   ...         ...
11543   Childers 1958-03-29      M  rep    MS    Democrat
11610     Taylor 1953-09-17      M  rep    MS    Democrat
11797   Nunnelee 1958-10-09      M  rep    MS  Republican
11873    Cochran 1937-12-07      M  sen    MS  Republican
11906     Harper 1956-06-01      M  rep    MS  Republican

[155 rows x 6 columns]
OL
    last_name   birthday gender type state party
404     Clark        NaT      M  rep    OL   NaN
503   Poydras 1740-04-03      M  rep    OL   NaN
IN
      last_name   birthday gender type state               party
431       Parke 1777-09-22      M  rep    IN                 NaN
985      Taylor        NaT      M  sen    IN          Republican
1089       Call        NaT      M  rep    IN  Jackson Republican
1130     Prince        NaT      M  rep    IN          Republican
1269      Blake 1792-06-14      M  rep    IN               Adams
...         ...        ...    ...  ...   ...                 ...
11807     Coats 1943-05-16      M  sen    IN          Republican
11847  Stutzman 1976-08-31      M  rep    IN          Republican
11897  Donnelly 1955-09-28      M  sen    IN            Democrat
11924    Rokita 1970-02-09      M  rep    IN          Republican
11940    Messer 1969-02-27      M  rep    IN          Republican

[341 rows x 6 columns]
LA
        last_name   birthday gender type state                  party
584     Destréhan        NaT      M  sen    LA                Unknown
585      Magruder        NaT      M  sen    LA             Republican
586         Posey 1750-07-09      M  sen    LA             Republican
620     Fromentin        NaT      M  sen    LA             Republican
814     Claiborne        NaT      M  sen    LA  Democratic Republican
...           ...        ...    ...  ...   ...                    ...
11739    Landrieu 1955-11-23      F  sen    LA               Democrat
11792  McAllister 1974-01-07      M  rep    LA             Republican
11811      Vitter 1961-05-03      M  sen    LA             Republican
11813    Boustany 1956-02-21      M  rep    LA             Republican
11823     Fleming 1951-07-05      M  rep    LA             Republican

[197 rows x 6 columns]
IL
        last_name   birthday gender type state       party
595          Bond 1773-11-24      M  rep    IL         NaN
772    Stephenson        NaT      M  rep    IL         NaN
861          Pope 1784-01-05      M  rep    IL         NaN
890       Edwards 1775-03-17      M  sen    IL  Republican
1146       Thomas        NaT      M  sen    IL       Adams
...           ...        ...    ...  ...   ...         ...
11808        Kirk 1959-09-15      M  sen    IL  Republican
11854        Dold 1969-06-23      M  rep    IL  Republican
11905   Gutiérrez 1953-12-10      M  rep    IL    Democrat
11908    Hultgren 1966-03-01      M  rep    IL  Republican
11927      Roskam 1961-09-13      M  rep    IL  Republican

[486 rows x 6 columns]
MO
       last_name   birthday gender type state       party
627    Hempstead 1780-06-03      M  rep    MO         NaN
712       Easton 1774-05-04      M  rep    MO         NaN
1174      Barton 1783-12-14      M  sen    MO       Adams
1236       Scott 1785-05-18      M  rep    MO       Adams
1266       Bates 1793-09-04      M  rep    MO       Adams
...          ...        ...    ...  ...   ...         ...
11601    Skelton 1931-12-20      M  rep    MO    Democrat
11651       Akin 1947-07-05      M  rep    MO  Republican
11668   Carnahan 1958-07-10      M  rep    MO    Democrat
11721    Emerson 1950-09-16      F  rep    MO  Republican
11885  McCaskill 1953-07-24      F  sen    MO    Democrat

[333 rows x 6 columns]
AL
      last_name   birthday gender type state       party
912     Crowell 1780-09-18      M  rep    AL  Republican
991      Walker 1783-08-12      M  sen    AL  Republican
1079      Kelly 1786-09-22      M  sen    AL  Republican
1180   Chambers 1790-10-01      M  sen    AL     Jackson
1252    Pickens 1780-01-30      M  sen    AL     Jackson
...         ...        ...    ...  ...   ...         ...
11557  Griffith 1942-08-06      M  rep    AL  Republican
11725    Bonner 1959-11-19      M  rep    AL  Republican
11745    Bachus 1947-12-28      M  rep    AL  Republican
11861  Sessions 1946-12-24      M  sen    AL  Republican
11870   Strange 1953-03-01      M  sen    AL  Republican

[206 rows x 6 columns]
AR
      last_name   birthday gender type state       party
1001      Bates 1788-08-25      M  rep    AR         NaN
1279     Conway 1793-03-18      M  rep    AR         NaN
2096     Fulton 1795-06-02      M  sen    AR    Democrat
2254      Cross 1798-11-11      M  rep    AR    Democrat
2318     Sevier 1801-11-04      M  sen    AR    Democrat
...         ...        ...    ...  ...   ...         ...
11531     Berry 1942-08-27      M  rep    AR    Democrat
11602    Snyder 1947-09-27      M  rep    AR    Democrat
11704      Ross 1961-08-02      M  rep    AR    Democrat
11741     Pryor 1963-01-10      M  sen    AR    Democrat
11758   Griffin 1968-08-21      M  rep    AR  Republican

[117 rows x 6 columns]
ME
        last_name   birthday gender type state       party
1019         Dane 1778-10-25      M  rep    ME  Federalist
1029       Harris 1779-01-27      M  rep    ME  Republican
1032         Hill 1772-06-30      M  rep    ME  Republican
1073      Whitman 1776-03-09      M  rep    ME  Federalist
1074   Williamson 1779-07-31      M  rep    ME  Republican
...           ...        ...    ...  ...   ...         ...
11275    Baldacci 1955-01-30      M  rep    ME    Democrat
11456       Allen 1945-04-16      M  rep    ME    Democrat
11646       Snowe 1947-02-21      F  sen    ME  Republican
11768     Michaud 1955-01-18      M  rep    ME    Democrat
11954    Poliquin 1953-11-01      M  rep    ME  Republican

[175 rows x 6 columns]
FL
           last_name   birthday gender type state       party
1031       Hernández 1788-05-26      M  rep    FL         NaN
1090            Call 1792-10-24      M  rep    FL         NaN
1781           White 1781-05-10      M  rep    FL         NaN
1948         Downing        NaT      M  rep    FL         NaN

In [2]:
import pandas as pd
import numpy as np
import datetime

In [3]:
df = (
    pd.read_csv("data-sets/airqual.csv",
                 na_values=-200)
    # .assign(reading_dt = datetime.datetime.strftime(df["Date"] + " " + df["Time"], "%m/%d/%y %H:%M:%S"))
    # .assign(reading_dt = df["Date"] + " " + df["Time"])
)
df["reading_dt"] = pd.to_datetime(df.pop("Date") + " " + df.pop("Time"), format = "%m/%d/%y %H:%M:%S" )
df.set_index("reading_dt", inplace=True)

In [18]:
def combine_dt(df):
    return (
        pd.to_datetime(df.pop("Date") + " " + df.pop("Time"), format = "%m/%d/%y %H:%M:%S" )
    )

In [19]:
df = (
    pd.read_csv("data-sets/airqual.csv",
                 na_values=[-200])
    .assign(reading_dt = combine_dt)
    .set_index("reading_dt")
    .drop(labels = ["PT08.S1(CO)", "NMHC(GT)", "C6H6(GT)", "PT08.S2(NMHC)", "NOx(GT)", "PT08.S3(NOx)", "NO2(GT)", "PT08.S4(NO2)", "PT08.S5(O3)"], axis = 1)
    .rename(columns = {"CO(GT)" : "co", "T" : "temp_c", "RH" : "rel_hum", "AH" : "abs_hum"})
)
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9357 entries, 2004-03-10 18:00:00 to 2005-04-04 14:00:00
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   co       7674 non-null   float64
 1   temp_c   8991 non-null   float64
 2   rel_hum  8991 non-null   float64
 3   abs_hum  8991 non-null   float64
dtypes: float64(4)
memory usage: 365.5 KB

In [186]:
df

                      co  temp_c  rel_hum  abs_hum
reading_dt
2004-03-10 18:00:00  2.6    13.6     48.9   0.7578
2004-03-10 19:00:00  2.0    13.3     47.7   0.7255
2004-03-10 20:00:00  2.2    11.9     54.0   0.7502
2004-03-10 21:00:00  2.2    11.0     60.0   0.7867
2004-03-10 22:00:00  1.6    11.2     59.6   0.7888
...                  ...     ...      ...      ...
2005-04-04 10:00:00  3.1    21.9     29.3   0.7568
2005-04-04 11:00:00  2.4    24.3     23.7   0.7119
2005-04-04 12:00:00  2.4    26.9     18.3   0.6406
2005-04-04 13:00:00  2.1    28.3     13.5   0.5139
2005-04-04 14:00:00  2.2    28.5     13.1   0.5028

[9357 rows x 4 columns]

In [73]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9357 entries, 2004-03-10 18:00:00 to 2005-04-04 14:00:00
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   co       7674 non-null   float64
 1   temp_c   8991 non-null   float64
 2   rel_hum  8991 non-null   float64
 3   abs_hum  8991 non-null   float64
dtypes: float64(4)
memory usage: 365.5 KB

In [72]:
df.shape

(9357, 4)

In [80]:
df["co"].head(25)

reading_dt
2004-03-10 18:00:00    2.6
2004-03-10 19:00:00    2.0
2004-03-10 20:00:00    2.2
2004-03-10 21:00:00    2.2
2004-03-10 22:00:00    1.6
2004-03-10 23:00:00    1.2
2004-03-11 00:00:00    1.2
2004-03-11 01:00:00    1.0
2004-03-11 02:00:00    0.9
2004-03-11 03:00:00    0.6
2004-03-11 04:00:00    NaN
2004-03-11 05:00:00    0.7
2004-03-11 06:00:00    0.7
2004-03-11 07:00:00    1.1
2004-03-11 08:00:00    2.0
2004-03-11 09:00:00    2.2
2004-03-11 10:00:00    1.7
2004-03-11 11:00:00    1.5
2004-03-11 12:00:00    1.6
2004-03-11 13:00:00    1.9
2004-03-11 14:00:00    2.9
2004-03-11 15:00:00    2.2
2004-03-11 16:00:00    2.2
2004-03-11 17:00:00    2.9
2004-03-11 18:00:00    4.8
Name: co, dtype: float64

In [88]:
df["co"].hasnans

True

In [13]:
day_names = df.index.day_name()

In [14]:
day_names

Index(['Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday',
       'Wednesday', 'Thursday', 'Thursday', 'Thursday', 'Thursday',
       ...
       'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday',
       'Monday', 'Monday', 'Monday'],
      dtype='str', name='reading_dt', length=9357)

In [107]:
data = {
    "Name": ['Bob',"Bob", "Bob", "Ishi", "Masimo"],
    "Fruit" : ["Apple", "Pear", "Apple", "Pear", "Pear"]
}

df2 = pd.DataFrame(data =data, index = [2,5,6,8,11])

In [108]:
df2

      Name  Fruit
2      Bob  Apple
5      Bob   Pear
6      Bob  Apple
8     Ishi   Pear
11  Masimo   Pear

In [109]:
mylist = ['a','b','c','a','b']

In [105]:
mygroup = df2.groupby(by = mylist)

In [110]:
for idx, group in mygroup:
    print(idx)
    print(group)
    print("\n\n")

a
   Name  Fruit
2   Bob  Apple
8  Ishi   Pear



b
      Name Fruit
5      Bob  Pear
11  Masimo  Pear



c
  Name  Fruit
6  Bob  Apple

In [114]:
df2.groupby(by = mylist, as_index=False)["Fruit"].count()

  index  Fruit
0     a      2
1     b      2
2     c      1

In [11]:
hr_index = df.index.hour
hr_index

Index([18, 19, 20, 21, 22, 23,  0,  1,  2,  3,
       ...
        5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype='int32', name='reading_dt', length=9357)

In [ ]:
df.groupby([day_names,hr_index])["co"].mean().rename_axis

reading_dt  reading_dt
Friday      0             1.936170
            1             1.608511
            2             1.172340
            3             0.887234
            4             0.823333
                            ...
Wednesday   19            4.146809
            20            3.844681
            21            2.897872
            22            2.102128
            23            1.938298
Name: co, Length: 168, dtype: float64

In [128]:
help(df.rename_axis)

Help on method rename_axis in module pandas.core.generic:

rename_axis(mapper: 'IndexLabel | lib.NoDefault' = <no_default>, *, index=<no_default>, columns=<no_default>, axis: 'Axis' = 0, copy: 'bool | lib.NoDefault' = <no_default>, inplace: 'bool' = False) -> 'Self | None' method of pandas.DataFrame instance
    Set the name of the axis for the index or columns.

    Parameters
    ----------
    mapper : scalar, list-like, optional
        Value to set the axis name attribute.

        Use either ``mapper`` and ``axis`` to
        specify the axis to target with ``mapper``, or ``index``
        and/or ``columns``.
    index : scalar, list-like, dict-like or function, optional
        A scalar, list-like, dict-like or functions transformations to
        apply to that axis' values.
    columns : scalar, list-like, dict-like or function, optional
        A scalar, list-like, dict-like or functions transformations to
        apply to that axis' values.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        The axis to rename.
    copy : bool, default False
        This keyword is now ignored; changing its value will have no
        impact on the method.

        .. deprecated:: 3.0.0

            This keyword is ignored and will be removed in pandas 4.0. Since
            pandas 3.0, this method always returns a new object using a lazy
            copy mechanism that defers copies until necessary
            (Copy-on-Write). See the `user guide on Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            for more details.

    inplace : bool, default False
        Modifies the object directly, instead of creating a new Series
        or DataFrame.

    Returns
    -------
    DataFrame, or None
        The same type as the caller or None if ``inplace=True``.

    See Also
    --------
    Series.rename : Alter Series index labels or name.
    DataFrame.rename : Alter DataFrame index labels or name.
    Index.rename : Set new names on index.

    Notes
    -----
    ``DataFrame.rename_axis`` supports two calling conventions

    * ``(index=index_mapper, columns=columns_mapper, ...)``
    * ``(mapper, axis={'index', 'columns'}, ...)``

    The first calling convention will only modify the names of
    the index and/or the names of the Index object that is the columns.
    In this case, the parameter ``copy`` is ignored.

    The second calling convention will modify the names of the
    corresponding index if mapper is a list or a scalar.
    However, if mapper is dict-like or a function, it will use the
    deprecated behavior of modifying the axis *labels*.

    We *highly* recommend using keyword arguments to clarify your
    intent.

    Examples
    --------
    **DataFrame**

    >>> df = pd.DataFrame(
    ...     {"num_legs": [4, 4, 2], "num_arms": [0, 0, 2]}, ["dog", "cat", "monkey"]
    ... )
    >>> df
            num_legs  num_arms
    dog            4         0
    cat            4         0
    monkey         2         2
    >>> df = df.rename_axis("animal")
    >>> df
            num_legs  num_arms
    animal
    dog            4         0
    cat            4         0
    monkey         2         2
    >>> df = df.rename_axis("limbs", axis="columns")
    >>> df
    limbs   num_legs  num_arms
    animal
    dog            4         0
    cat            4         0
    monkey         2         2

    **MultiIndex**

    >>> df.index = pd.MultiIndex.from_product(
    ...     [["mammal"], ["dog", "cat", "monkey"]], names=["type", "name"]
    ... )
    >>> df
    limbs          num_legs  num_arms
    type   name
    mammal dog            4         0
           cat            4         0
           monkey         2         2

    >>> df.rename_axis(index={"type": "class"})
    limbs          num_legs  num_arms
    class  name
    mammal dog            4         0
           cat            4         0
           monkey         2         2

    >>> df.rename_axis(columns=str.upper)
    LIMBS          num_legs  num_arms
    type   name
    mammal dog            4         0
           cat            4         0
           monkey         2         2

In [135]:
import pandas as pd

# Create a sample DataFrame
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
display(df)
# The index and columns initially have no name
print("Original DataFrame index name:", df.index.name)
print("Original DataFrame columns name:", df.columns.name)

# Rename the index axis to 'Row Labels'
df_renamed_index = df.rename_axis(index='Row Labels')
display(df_renamed_index)
# Rename the columns axis to 'Column Features'
df_renamed_columns = df.rename_axis(columns='Column Features', index='Row Labels')
display(df_renamed_columns)
print("\nDataFrame with renamed index axis name:")
print(df_renamed_index.index.name) # Output: Row Labels

print("\nDataFrame with renamed columns axis name:")
print(df_renamed_columns.columns.name) # Output: Column Features

   A  B
0  1  3
1  2  4

Original DataFrame index name: None
Original DataFrame columns name: None

            A  B
Row Labels
0           1  3
1           2  4

Column Features  A  B
Row Labels
0                1  3
1                2  4

DataFrame with renamed index axis name:
Row Labels

DataFrame with renamed columns axis name:
Column Features

In [178]:
import pandas as pd
s1 = pd.Series([1, 2], index=['a', 'b'])
s2 = pd.Series([3, 4], index=['b', 'c'])

# Default join='outer' (union of indices)
a, b = s1.align(s2)
# a: a 1.0, b 2.0, c NaN; b: a NaN, b 3.0, c 4.0
display(s1.align(s2))
display(a)
display(b)

(a    1.0
 b    2.0
 c    NaN
 dtype: float64,
 a    NaN
 b    3.0
 c    4.0
 dtype: float64)

a    1.0
b    2.0
c    NaN
dtype: float64

a    NaN
b    3.0
c    4.0
dtype: float64

In [163]:
data = {
    "Name": ['Asha',"Bob", "Charlie", "David", "Elisa"],
    "Fruit" : ["Apple", "Pear", "Apple", "Pear", "Pear"]
}

df2 = pd.DataFrame(data =data, index = [2,5,6,8,11])

In [164]:
df2

       Name  Fruit
2      Asha  Apple
5       Bob   Pear
6   Charlie  Apple
8     David   Pear
11    Elisa   Pear

In [165]:
def fruit_cat(s):
    # print(s)
    # return 'sweet'
    if s.iloc[1] == 'Apple':
        return 'Sweet'
    elif s.iloc[1] == 'Pear':
        return 'Sour'

In [168]:
fruit_categories = df2.apply(fruit_cat, axis = 1)
fruit_categories

2     Sweet
5      Sour
6     Sweet
8      Sour
11     Sour
dtype: str

In [182]:
fruit_categories2 = pd.Series(
    index = [2,5,6,12,13],
    data = ['Sweet','Sour','Sweet', 'Sour', 'Sour']
)
fruit_categories2

2     Sweet
5      Sour
6     Sweet
12     Sour
13     Sour
dtype: str

In [171]:
fruit_group = df2.groupby(fruit_categories)

In [172]:
for cat, group in fruit_group:
    print(cat)
    print(group)
    print("\n")

Sour
     Name Fruit
5     Bob  Pear
8   David  Pear
11  Elisa  Pear


Sweet
      Name  Fruit
2     Asha  Apple
6  Charlie  Apple

In [183]:
fruit_group2 = df2.groupby(fruit_categories2)

In [184]:
for cat, group in fruit_group2:
    print(cat)
    print(group)
    print("\n")

Sour
  Name Fruit
5  Bob  Pear


Sweet
      Name  Fruit
2     Asha  Apple
6  Charlie  Apple

In [187]:
df

                      co  temp_c  rel_hum  abs_hum
reading_dt
2004-03-10 18:00:00  2.6    13.6     48.9   0.7578
2004-03-10 19:00:00  2.0    13.3     47.7   0.7255
2004-03-10 20:00:00  2.2    11.9     54.0   0.7502
2004-03-10 21:00:00  2.2    11.0     60.0   0.7867
2004-03-10 22:00:00  1.6    11.2     59.6   0.7888
...                  ...     ...      ...      ...
2005-04-04 10:00:00  3.1    21.9     29.3   0.7568
2005-04-04 11:00:00  2.4    24.3     23.7   0.7119
2005-04-04 12:00:00  2.4    26.9     18.3   0.6406
2005-04-04 13:00:00  2.1    28.3     13.5   0.5139
2005-04-04 14:00:00  2.2    28.5     13.1   0.5028

[9357 rows x 4 columns]

In [188]:
df['temp_c'].describe()

count    8991.000000
mean       18.317829
std         8.832116
min        -1.900000
25%        11.800000
50%        17.800000
75%        24.400000
max        44.600000
Name: temp_c, dtype: float64

In [189]:
def categorize_temp(row):
    if row['temp_c'] <= 17:
        return 'cool'
    elif row['temp_c'] <= 25:
        return 'warm'
    else:
        return 'hot'

In [191]:
temp_categories = df.apply(categorize_temp, axis = 1)

In [192]:
categories = df.groupby(temp_categories)

In [193]:
for cat, group in categories:
    print(cat)
    print(group)
    print("\n")

cool
                      co  temp_c  rel_hum  abs_hum
reading_dt
2004-03-10 18:00:00  2.6    13.6     48.9   0.7578
2004-03-10 19:00:00  2.0    13.3     47.7   0.7255
2004-03-10 20:00:00  2.2    11.9     54.0   0.7502
2004-03-10 21:00:00  2.2    11.0     60.0   0.7867
2004-03-10 22:00:00  1.6    11.2     59.6   0.7888
...                  ...     ...      ...      ...
2005-04-04 04:00:00  NaN    11.8     56.0   0.7743
2005-04-04 05:00:00  0.5    10.4     59.9   0.7550
2005-04-04 06:00:00  1.1     9.5     63.1   0.7531
2005-04-04 07:00:00  4.0     9.7     61.9   0.7446
2005-04-04 08:00:00  5.0    13.5     48.9   0.7553

[4267 rows x 4 columns]


hot
                      co  temp_c  rel_hum  abs_hum
reading_dt
2004-03-16 13:00:00  4.0    25.3     26.1   0.8264
2004-03-16 14:00:00  3.8    25.8     23.2   0.7589
2004-03-16 15:00:00  2.8    27.0     20.2   0.7094
2004-03-16 16:00:00  2.9    28.2     18.6   0.7014
2004-03-16 17:00:00  2.9    28.0     19.1   0.7098
...                  ...     ...      ...      ...
2005-04-03 16:00:00  1.3    29.4     10.4   0.4192
2005-04-03 17:00:00  1.4    28.9      9.9   0.3866
2005-04-04 12:00:00  2.4    26.9     18.3   0.6406
2005-04-04 13:00:00  2.1    28.3     13.5   0.5139
2005-04-04 14:00:00  2.2    28.5     13.1   0.5028

[2425 rows x 4 columns]


warm
                      co  temp_c  rel_hum  abs_hum
reading_dt
2004-03-13 12:00:00  3.6    18.4     33.8   0.7090
2004-03-13 13:00:00  2.8    19.4     31.3   0.6950
2004-03-13 14:00:00  2.0    18.0     34.8   0.7127
2004-03-13 15:00:00  2.0    18.4     33.6   0.7042
2004-03-13 16:00:00  2.5    17.6     35.1   0.7012
...                  ...     ...      ...      ...
2005-04-03 19:00:00  2.7    19.9     33.0   0.7608
2005-04-03 20:00:00  2.5    17.5     40.7   0.8073
2005-04-04 09:00:00  3.9    18.2     36.3   0.7487
2005-04-04 10:00:00  3.1    21.9     29.3   0.7568
2005-04-04 11:00:00  2.4    24.3     23.7   0.7119

[2665 rows x 4 columns]

In [196]:
df.groupby(temp_categories)['abs_hum'].mean()

cool    0.760215
hot     1.322019
warm    1.221264
Name: abs_hum, dtype: float64

In [4]:
df

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
reading_dt,,,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
2004-03-10 19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2004-03-10 20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
2004-03-10 21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
2004-03-10 22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-04-04 10:00:00,3.1,1314.0,NaN,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
2005-04-04 11:00:00,2.4,1163.0,NaN,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
2005-04-04 12:00:00,2.4,1142.0,NaN,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
2005-04-04 13:00:00,2.1,1003.0,NaN,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
2005-04-04 14:00:00,2.2,1071.0,NaN,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

In [20]:
yr = df.index.year
yr

Index([2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004,
       ...
       2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005],
      dtype='int32', name='reading_dt', length=9357)

In [21]:
qtr = df.index.quarter

In [22]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9357 entries, 2004-03-10 18:00:00 to 2005-04-04 14:00:00
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   co       7674 non-null   float64
 1   temp_c   8991 non-null   float64
 2   rel_hum  8991 non-null   float64
 3   abs_hum  8991 non-null   float64
dtypes: float64(4)
memory usage: 365.5 KB

In [32]:
df["co"].groupby([yr, qtr]).agg(["mean","median"]).rename_axis(["year", "Qtr"], axis = 0)

              mean  median
year Qtr
2004 1    2.292073     2.1
     2    2.029174     1.8
     3    1.766122     1.5
     4    2.719042     2.4
2005 1    2.090451     1.7
     2    1.205882     1.0

In [33]:
df.index.min()

Timestamp('2004-03-10 18:00:00')

In [ ]:
df.resample(rule = "QE").asfreq()["co"].agg(["mean","median"])

                mean  median
reading_dt
2004-03-31  2.292073     2.1
2004-06-30  2.029174     1.8
2004-09-30  1.766122     1.5
2004-12-31  2.719042     2.4
2005-03-31  2.090451     1.7
2005-06-30  1.205882     1.0

In [49]:
df.resample(rule = "QE").agg(["mean","median"])

                  co            temp_c           rel_hum          abs_hum  \
                mean median       mean median       mean median      mean
reading_dt
2004-03-31  2.292073    2.1  14.390784  14.05  50.170784   52.2  0.789413
2004-06-30  2.029174    1.8  21.142613  20.20  44.705511   44.6  1.048341
2004-09-30  1.766122    1.5  27.751168  26.80  39.865467   39.5  1.379070
2004-12-31  2.719042    2.4  15.202962  14.90  59.742454   61.4  1.073292
2005-03-31  2.090451    1.7   9.731652   8.80  53.165776   53.1  0.654305
2005-06-30  1.205882    1.0  16.660920  15.10  35.482759   35.6  0.621592


             median
reading_dt
2004-03-31  0.79205
2004-06-30  1.01850
2004-09-30  1.35745
2004-12-31  1.06090
2005-03-31  0.63640
2005-06-30  0.59770

In [67]:
import time

In [79]:
def convert_time(df):
    return pd.to_datetime(df["tstamp"],unit = 'ms')

In [87]:
df = (pd.read_csv("data-sets/news.csv", 
             delimiter="\t", 
             index_col=0, 
             usecols=[0,1,2,3,6,7],
             names = ['id','title','url','newspaper','website', 'tstamp'])
.assign(tstamp = convert_time)
.astype(dtype = {
    "newspaper" : "category",
    "website" : "category"
})
)

In [107]:
df["title"].head(10)

id
1     Fed official says weak data caused by weather,...
2     Fed's Charles Plosser sees high bar for change...
3     US open: Stocks fall after Fed official hints ...
4     Fed risks falling 'behind the curve', Charles ...
5     Fed's Plosser: Nasty Weather Has Curbed Job Gr...
6     Plosser: Fed May Have to Accelerate Tapering Pace
7             Fed's Plosser: Taper pace may be too slow
8     Fed's Plosser expects US unemployment to fall ...
9     US jobs growth last month hit by weather:Fed P...
10    ECB unlikely to end sterilisation of SMP purch...
Name: title, dtype: str

In [90]:
df["website"].value_counts()

website
in.reuters.com            2877
www.huffingtonpost.com    2603
www.businessweek.com      2420
www.contactmusic.com      2334
www.dailymail.co.uk       2258
                          ...
ysnews.com                   1
yumanewsnow.com              1
zik.com.ua                   1
zik.ua                       1
zumic.com                    1
Name: count, Length: 11236, dtype: int64

In [68]:
x = lambda s : time.ctime(s)

In [76]:
# x(1409229190771)

time.ctime(1772182671.90299)
# time.time()

'Fri Feb 27 14:27:51 2026'

In [91]:
df.info()

<class 'pandas.DataFrame'>
Index: 422419 entries, 1 to 422937
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   title      422419 non-null  str
 1   url        422419 non-null  str
 2   newspaper  422417 non-null  category
 3   website    422419 non-null  category
 4   tstamp     422419 non-null  datetime64[ms]
dtypes: category(2), datetime64[ms](1), str(2)
memory usage: 14.9 MB

In [99]:
df[df["title"].str.contains("Fed")].groupby("newspaper")['tstamp'].count().nlargest(10)

newspaper
Reuters                         161
NASDAQ                          103
Businessweek                     93
Investing.com                    66
Wall Street Journal \(blog\)     61
MarketWatch                      56
Moneynews                        55
Bloomberg                        53
GlobalPost                       51
Economic Times                   44
Name: tstamp, dtype: int64

In [116]:
df.groupby("newspaper", sort = False)["title"].apply(lambda ser : ser.str.contains("Fed").sum())

newspaper
Los Angeles Times        17
Livemint                 11
IFA Magazine             26
Moneynews                55
NASDAQ                  103
                       ...
Compensation.BLR.com      0
Georgia Bulletin          0
YOU.co.za                 0
Just Football.com         0
Journeyman Weekly         0
Name: title, Length: 10985, dtype: int64

In [125]:
df.groupby("newspaper")["title"].apply(lambda ser: ser.str.contains("Fed")).index

MultiIndex([(                             '100.7 WZLX Classic Rock',   6416),
            (                             '100.7 WZLX Classic Rock',  55186),
            (                             '100.7 WZLX Classic Rock', 227869),
            (                             '100.7 WZLX Classic Rock', 249156),
            (                             '100.7 WZLX Classic Rock', 257466),
            (                             '100.7 WZLX Classic Rock', 313966),
            (                             '100.7 WZLX Classic Rock', 319371),
            (                             '100.7 WZLX Classic Rock', 334959),
            (                             '100.7 WZLX Classic Rock', 338103),
            (                             '100.7 WZLX Classic Rock', 366528),
            ...
            ('«Market Leader» - news and previews making you rich.', 250242),
            ('«Market Leader» - news and previews making you rich.', 263771),
            ('«Market Leader» - news and previews making you rich.', 263803),
            ('«Market Leader» - news and previews making you rich.', 263804),
            ('«Market Leader» - news and previews making you rich.', 263805),
            ('«Market Leader» - news and previews making you rich.', 263806),
            ('«Market Leader» - news and previews making you rich.', 272679),
            ('«Market Leader» - news and previews making you rich.', 315511),
            ('«Market Leader» - news and previews making you rich.', 334438),
            ('«Market Leader» - news and previews making you rich.', 353547)],
           names=['newspaper', 'id'], length=422417)

In [ ]:
df.groupby