In [14]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

GOAL: COMPUTE FINAL GRADE OF EACH STUDENT IN A LARGE COURSE (150 STUDENTS)
- The data is in various csv files
- Grade is computed using several asessments (homework, quizzes, exams). Each assessment will have a wt.

### hw_exam_df Dataframe

In [144]:
hw_exam_df = (
    pd.read_csv("data-sets/gradebook_data/hw_exam_grades.csv")
    .rename(columns = lambda label : str(label).lower().replace(" ", "_").replace("_-_","_"))
    .assign(homework_1 = lambda df : df["homework_1"].fillna(0).astype(dtype = {"homework_1" : np.int64}))
    )

req_columns = [col for col in hw_exam_df.columns if "_time" not in col]

hw_exam_df = hw_exam_df[req_columns]

In [145]:
hw_exam_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   first_name              150 non-null    str
 1   last_name               150 non-null    str
 2   sid                     150 non-null    str
 3   homework_1              150 non-null    int64
 4   homework_1_max_points   150 non-null    int64
 5   homework_2              150 non-null    int64
 6   homework_2_max_points   150 non-null    int64
 7   homework_3              150 non-null    int64
 8   homework_3_max_points   150 non-null    int64
 9   homework_4              150 non-null    int64
 10  homework_4_max_points   150 non-null    int64
 11  homework_5              150 non-null    int64
 12  homework_5_max_points   150 non-null    int64
 13  homework_6              150 non-null    int64
 14  homework_6_max_points   150 non-null    int64
 15  homework_7              150 non-null    int64
 16  homework_7_max_points   150 non-null    int64
 17  homework_8              150 non-null    int64
 18  homework_8_max_points   150 non-null    int64
 19  homework_9              150 non-null    int64
 20  homework_9_max_points   150 non-null    int64
 21  homework_10             150 non-null    int64
 22  homework_10_max_points  150 non-null    int64
 23  exam_1                  150 non-null    int64
 24  exam_1_max_points       150 non-null    int64
 25  exam_2                  150 non-null    int64
 26  exam_2_max_points       150 non-null    int64
 27  exam_3                  150 non-null    int64
 28  exam_3_max_points       150 non-null    int64
dtypes: int64(26), str(3)
memory usage: 34.1 KB

In [132]:
# pd.to_datetime(hw_exam_df["homework_1_submission_time"]).describe()
hw_exam_df["exam_3_submission_time"].value_counts()

exam_3_submission_time
2019-12-08 12:30:07-07:00    150
Name: count, dtype: int64

In [15]:
hw_exam_df[hw_exam_df["Homework 1"].isna() == True]

,First Name,Last Name,SID,Homework 1,Homework 1 - Max Points,Homework 1 - Submission Time,Homework 2,Homework 2 - Max Points,Homework 2 - Submission Time,Homework 3,Homework 3 - Max Points,Homework 3 - Submission Time,Homework 4,Homework 4 - Max Points,Homework 4 - Submission Time,Homework 5,Homework 5 - Max Points,Homework 5 - Submission Time,Homework 6,Homework 6 - Max Points,Homework 6 - Submission Time,Homework 7,Homework 7 - Max Points,Homework 7 - Submission Time,Homework 8,Homework 8 - Max Points,Homework 8 - Submission Time,Homework 9,Homework 9 - Max Points,Homework 9 - Submission Time,Homework 10,Homework 10 - Max Points,Homework 10 - Submission Time,Exam 1,Exam 1 - Max Points,Exam 1 - Submission Time,Exam 2,Exam 2 - Max Points,Exam 2 - Submission Time,Exam 3,Exam 3 - Max Points,Exam 3 - Submission Time
144,Traci,Joyce,txj12345,NaN,80,2019-08-29 08:56:02-07:00,77,80,2019-09-05 08:56:02-07:00,58,80,2019-09-12 08:56:02-07:00,91,100,2019-09-19 08:56:02-07:00,66,70,2019-09-26 08:56:02-07:00,78,90,2019-10-03 08:56:02-07:00,30,50,2019-10-10 08:56:02-07:00,69,70,2019-10-17 08:56:02-07:00,59,60,2019-10-24 08:56:02-07:00,53,60,2019-10-31 08:56:02-07:00,100,100,2019-10-08 12:30:07-07:00,84,100,2019-11-08 12:30:07-07:00,64,100,2019-12-08 12:30:07-07:00

In [16]:
hw_exam_df["SID"].is_unique

True

In [68]:
dtypes = {
    "grade" : np.int8
}

In [91]:
quiz1_df = pd.read_csv("data-sets/gradebook_data/quiz_1_grades.csv", header = None, skiprows=1,
                       names = ["last_name","first_name","email", "grade_1"],
                       dtype = {
                           "grade_1" : np.int8
                           })

In [77]:
quiz1_df.head(10)

  last_name first_name                      email  grade
0   Bennett    Richard   richard.bennett@univ.edu     10
1    Parker    Timothy    timothy.parker@univ.edu      9
2     Reyes      Carol       carol.reyes@univ.edu      5
3    Powers     Brooke     brooke.powers@univ.edu      6
4    Taylor    Michael    michael.taylor@univ.edu      5
5    Bailey    Belinda    belinda.bailey@univ.edu      6
6   Stevens     Marcia    marcia.stevens@univ.edu      7
7  Faulkner    Katelyn  katelyn.faulkner@univ.edu      6
8    Daniel    William    william.daniel@univ.edu      9
9   Johnson      Dylan     dylan.johnson@univ.edu      6

In [71]:
quiz1_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   last_name   150 non-null    str
 1   first_name  150 non-null    str
 2   email       150 non-null    str
 3   grade       150 non-null    int8
dtypes: int8(1), str(3)
memory usage: 3.8 KB

In [20]:
quiz1_df["Grade"].describe()

count    150.000000
mean       7.413333
std        2.127439
min        4.000000
25%        6.000000
50%        7.000000
75%        9.000000
max       11.000000
Name: Grade, dtype: float64

In [22]:
quiz1_df[quiz1_df["Grade"] == 11]

      Last Name First Name                         Email  Grade
13     Schwartz      Billy       billy.schwartz@univ.edu     11
18    Hernandez     Taylor     taylor.hernandez@univ.edu     11
21   Washington     Travis    travis.washington@univ.edu     11
40    Rodriguez  Alexander  alexander.rodriguez@univ.edu     11
72    Wilkerson       Levi       levi.wilkerson@univ.edu     11
100     Simpson    Felicia      felicia.simpson@univ.edu     11
110        Odom       John            john.odom@univ.edu     11
111        Mann     Nicole          nicole.mann@univ.edu     11
121      Mccall   Kimberly      kimberly.mccall@univ.edu     11
125     Miranda      Brett        brett.miranda@univ.edu     11
133      Watson      Holly         holly.watson@univ.edu     11
137     Woodard       John         john.woodard@univ.edu     11

In [92]:
quiz2_df = pd.read_csv("data-sets/gradebook_data/quiz_2_grades.csv", header = None, skiprows=1,
                       names = ["last_name","first_name","email", "grade_2"],
                       dtype = {
                           "grade_2" : np.int8
                           })

In [93]:
quiz2_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   last_name   150 non-null    str
 1   first_name  150 non-null    str
 2   email       150 non-null    str
 3   grade_2     150 non-null    int8
dtypes: int8(1), str(3)
memory usage: 3.8 KB

In [25]:
quiz2_df.describe()

            Grade
count  150.000000
mean    10.886667
std      2.945903
min      6.000000
25%      8.000000
50%     11.000000
75%     14.000000
max     15.000000

In [94]:
quiz3_df = pd.read_csv("data-sets/gradebook_data/quiz_3_grades.csv", header = None, skiprows=1,
                       names = ["last_name","first_name","email", "grade_3"],
                       dtype = {
                           "grade_3" : np.int8
                           })

In [81]:
quiz3_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   last_name   150 non-null    str
 1   first_name  150 non-null    str
 2   email       150 non-null    str
 3   grade       150 non-null    int8
dtypes: int8(1), str(3)
memory usage: 3.8 KB

In [28]:
quiz3_df.describe()

            Grade
count  150.000000
mean    11.640000
std      3.458828
min      6.000000
25%      9.000000
50%     12.000000
75%     14.000000
max     17.000000

In [95]:
quiz4_df = pd.read_csv("data-sets/gradebook_data/quiz_4_grades.csv", header = None, skiprows=1,
                       names = ["last_name","first_name","email", "grade_4"],
                       dtype = {
                           "grade_4" : np.int8
                           })

In [83]:
quiz4_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   last_name   150 non-null    str
 1   first_name  150 non-null    str
 2   email       150 non-null    str
 3   grade       150 non-null    int8
dtypes: int8(1), str(3)
memory usage: 3.8 KB

In [30]:
quiz4_df.describe()

            Grade
count  150.000000
mean     9.506667
std      2.928102
min      5.000000
25%      7.000000
50%      9.500000
75%     12.000000
max     14.000000

In [96]:
quiz5_df = pd.read_csv("data-sets/gradebook_data/quiz_5_grades.csv", header = None, skiprows=1,
                       names = ["last_name","first_name","email", "grade_5"],
                       dtype = {
                           "grade_5" : np.int8
                           })

In [85]:
quiz5_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   last_name   150 non-null    str
 1   first_name  150 non-null    str
 2   email       150 non-null    str
 3   grade       150 non-null    int8
dtypes: int8(1), str(3)
memory usage: 3.8 KB

In [86]:
quiz5_df.describe()

            grade
count  150.000000
mean     7.853333
std      2.668199
min      4.000000
25%      5.250000
50%      8.000000
75%     10.000000
max     12.000000

In [98]:
from functools import reduce

# Put DataFrames in a list
dfs = [quiz1_df, quiz2_df, quiz3_df, quiz4_df, quiz5_df]

# Merge all DataFrames on the 'name' column using an outer join
quiz_df = reduce(lambda left, right: pd.merge(left, right, on=['last_name', 'first_name', 'email' ], how='outer'), dfs)

print(quiz_df)

     last_name first_name                       email  grade_1  grade_2  \
0        Adams        Amy          amy.adams@univ.edu        9       11
1        Allen  Christina    christina.allen@univ.edu       10       12
2     Anderson      Daisy     daisy.anderson@univ.edu        9        6
3     Anderson     Lauren    lauren.anderson@univ.edu        8        6
4       Bailey    Belinda     belinda.bailey@univ.edu        6       10
..         ...        ...                         ...      ...      ...
145  Wilkerson       Levi     levi.wilkerson@univ.edu       11       13
146   Williams   Kimberly  kimberly.williams@univ.edu        6        6
147       Wolf   Courtney      courtney.wolf@univ.edu       10       15
148    Woodard       John       john.woodard@univ.edu       11       14
149      Young     Joseph       joseph.young@univ.edu        8       14

     grade_3  grade_4  grade_5
0         12        8       10
1         14       14        8
2         10        6        7
3         11       11        6
4          9       14        4
..       ...      ...      ...
145        8       14       12
146       11       11        9
147        9        7        9
148       11       13        8
149       12       11       10

[150 rows x 8 columns]

In [99]:
quiz_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   last_name   150 non-null    str
 1   first_name  150 non-null    str
 2   email       150 non-null    str
 3   grade_1     150 non-null    int8
 4   grade_2     150 non-null    int8
 5   grade_3     150 non-null    int8
 6   grade_4     150 non-null    int8
 7   grade_5     150 non-null    int8
dtypes: int8(5), str(3)
memory usage: 4.4 KB

###### +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### hw_exam_df Dataframe

In [184]:
hw_exam_df = (
    pd.read_csv("data-sets/gradebook_data/hw_exam_grades.csv")
    .rename(columns = lambda label : str(label).lower().replace(" ", "_").replace("_-_","_"))
    .assign(homework_1 = lambda df : df["homework_1"].fillna(0).astype(dtype = {"homework_1" : np.int64}))
    )

req_columns = [col for col in hw_exam_df.columns if "_time" not in col]

hw_exam_df = hw_exam_df[req_columns]

In [185]:
hw_exam_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   first_name              150 non-null    str
 1   last_name               150 non-null    str
 2   sid                     150 non-null    str
 3   homework_1              150 non-null    int64
 4   homework_1_max_points   150 non-null    int64
 5   homework_2              150 non-null    int64
 6   homework_2_max_points   150 non-null    int64
 7   homework_3              150 non-null    int64
 8   homework_3_max_points   150 non-null    int64
 9   homework_4              150 non-null    int64
 10  homework_4_max_points   150 non-null    int64
 11  homework_5              150 non-null    int64
 12  homework_5_max_points   150 non-null    int64
 13  homework_6              150 non-null    int64
 14  homework_6_max_points   150 non-null    int64
 15  homework_7              150 non-null    int64
 16  homework_7_max_points   150 non-null    int64
 17  homework_8              150 non-null    int64
 18  homework_8_max_points   150 non-null    int64
 19  homework_9              150 non-null    int64
 20  homework_9_max_points   150 non-null    int64
 21  homework_10             150 non-null    int64
 22  homework_10_max_points  150 non-null    int64
 23  exam_1                  150 non-null    int64
 24  exam_1_max_points       150 non-null    int64
 25  exam_2                  150 non-null    int64
 26  exam_2_max_points       150 non-null    int64
 27  exam_3                  150 non-null    int64
 28  exam_3_max_points       150 non-null    int64
dtypes: int64(26), str(3)
memory usage: 34.1 KB

### quiz_df Dataframe

In [186]:
from pathlib import Path

# Create a Path object for your directory
base_path = Path("./data-sets/gradebook_data/")

# Use .glob() for non-recursive matching in the current directory
# Pattern to find files that start with "report"
files_matching_name = list(base_path.glob("quiz_*"))
# print(files_matching_name)

# Use .rglob() for recursive matching (all subdirectories)
# Pattern to find all files ending with ".csv" in the directory tree
recursive_files = list(base_path.rglob("quiz_*"))
# print(recursive_files)

dfs = []

# Print the list of Path objects (which can be used as strings)
for idx, file_path in enumerate(files_matching_name):
    # print(file_path)
    df_name = f"quiz{idx+1}_df"
    # dfs.append(df_name)
    grade_col = f"quiz_grade_{idx+1}"
    df_name = pd.read_csv(file_path, header = None, skiprows=1,
                       names = ["last_name","first_name","email", grade_col],
                       dtype = {
                           grade_col : np.int8
                           })
    dfs.append(df_name)


# Merge all DataFrames on the 'name' column using an outer join
quiz_df = reduce(lambda left, right: pd.merge(left, right, on=['last_name', 'first_name', 'email' ], how='outer'), dfs)

print(quiz_df)

     last_name first_name                       email  quiz_grade_1  \
0        Adams        Amy          amy.adams@univ.edu             9
1        Allen  Christina    christina.allen@univ.edu            10
2     Anderson      Daisy     daisy.anderson@univ.edu             9
3     Anderson     Lauren    lauren.anderson@univ.edu             8
4       Bailey    Belinda     belinda.bailey@univ.edu             6
..         ...        ...                         ...           ...
145  Wilkerson       Levi     levi.wilkerson@univ.edu            11
146   Williams   Kimberly  kimberly.williams@univ.edu             6
147       Wolf   Courtney      courtney.wolf@univ.edu            10
148    Woodard       John       john.woodard@univ.edu            11
149      Young     Joseph       joseph.young@univ.edu             8

     quiz_grade_2  quiz_grade_3  quiz_grade_4  quiz_grade_5
0              11            12             8            10
1              12            14            14             8
2               6            10             6             7
3               6            11            11             6
4              10             9            14             4
..            ...           ...           ...           ...
145            13             8            14            12
146             6            11            11             9
147            15             9             7             9
148            14            11            13             8
149            14            12            11            10

[150 rows x 8 columns]

In [189]:
hw_exam_df.loc[hw_exam_df["sid"] == "jgf12345", 'first_name'] = 'John'
# hw_exam_df.loc[hw_exam_df["sid"] == "jgf12345"]

In [190]:
df = pd.merge(hw_exam_df, quiz_df, on=['last_name', 'first_name'], how='outer')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   first_name              150 non-null    str
 1   last_name               150 non-null    str
 2   sid                     150 non-null    str
 3   homework_1              150 non-null    int64
 4   homework_1_max_points   150 non-null    int64
 5   homework_2              150 non-null    int64
 6   homework_2_max_points   150 non-null    int64
 7   homework_3              150 non-null    int64
 8   homework_3_max_points   150 non-null    int64
 9   homework_4              150 non-null    int64
 10  homework_4_max_points   150 non-null    int64
 11  homework_5              150 non-null    int64
 12  homework_5_max_points   150 non-null    int64
 13  homework_6              150 non-null    int64
 14  homework_6_max_points   150 non-null    int64
 15  homework_7              150 non-null    int64
 16  homework_7_max_points   150 non-null    int64
 17  homework_8              150 non-null    int64
 18  homework_8_max_points   150 non-null    int64
 19  homework_9              150 non-null    int64
 20  homework_9_max_points   150 non-null    int64
 21  homework_10             150 non-null    int64
 22  homework_10_max_points  150 non-null    int64
 23  exam_1                  150 non-null    int64
 24  exam_1_max_points       150 non-null    int64
 25  exam_2                  150 non-null    int64
 26  exam_2_max_points       150 non-null    int64
 27  exam_3                  150 non-null    int64
 28  exam_3_max_points       150 non-null    int64
 29  email                   150 non-null    str
 30  quiz_grade_1            150 non-null    int8
 31  quiz_grade_2            150 non-null    int8
 32  quiz_grade_3            150 non-null    int8
 33  quiz_grade_4            150 non-null    int8
 34  quiz_grade_5            150 non-null    int8
dtypes: int64(26), int8(5), str(4)
memory usage: 36.0 KB